import type { Locale } from "@/i18n/routing";

const productCopy = {
  en: {
    eyebrow: "VALRUN / AI-WORK UNDERWRITING",
    headline: "Know if an AI task is worth running.",
    introduction: "Describe the work. Valrun maps the capabilities, checks observed AI-service supply, and tests cost and risk before you commit.",
    inspectAction: "INSPECT LIVE WORK",
    underwriteAction: "ANALYZE A TASK",
    openForge: "OPEN THE FULL FORGE",
    quickLabel: "YOUR TASK / START HERE",
    quickPlaceholder: "What should the agent deliver?",
    quickHint: "No account required · no task runs until you explicitly authorize it",
    evidenceLabel: "A REAL MARKET OBSERVATION",
    evidenceQuestion: "What does the evidence actually say?",
    observedFact: "OBSERVED",
    rewardLabel: "REWARD",
    spendLabel: "KNOWN SPEND",
    decisionLabel: "CURRENT READ",
    unknown: "UNKNOWN",
    notEligible: "NOT ELIGIBLE",
    insufficientData: "INSUFFICIENT DATA",
    evidenceCaveat: "A listing is not a profit forecast. Missing route costs stay unknown until you underwrite the task.",
    noObservation: "No current paid work in this view.",
    methodHeading: "From an objective to a defensible decision.",
    methodIntroduction: "Each step narrows what is known. You choose the assumptions; the server calculates the economics.",
    methodOutcome: "CURRENT STEP",
    boundariesLabel: "Valrun boundaries",
    controlsLabel: "Profit Engine controls",
    marketPulse: "MARKET SNAPSHOT",
    observedListings: "observed listings",
    paidOpportunities: "paid opportunities in this view",
    methodLabel: "FROM TASK TO DECISION",
    methodSteps: [
      { title: "Describe the work", detail: "Bring your own objective, even when the market has no eligible work." },
      { title: "Inspect the route", detail: "See required capabilities and what observed services can—and cannot—prove." },
      { title: "Test the economics", detail: "Set your assumptions; receive a conditional decision and receipt." },
    ],
    liveWork: "LIVE OBSERVED WORK",
    cachedWork: "CACHED OBSERVED WORK",
    sourceStatus: "OBSERVATION STATUS",
    loading: "Refreshing bounded market observations…",
    unavailable: "Live observations are unavailable. No substitute was inserted.",
    empty: "No qualifying observed work is available in this bounded snapshot.",
    emptyDetail: "Unknown inventory remains unknown. Valrun never substitutes a demonstration opportunity on the live homepage.",
    openRadar: "OPEN LIVE RADAR",
    productEntry: "PRODUCT ENTRY POINTS",
    entryTitle: "Continue with the evidence.",
    radar: "LIVE RADAR",
    radarDetail: "Inspect bounded observed opportunities and source eligibility.",
    forge: "UNDERWRITING",
    forgeDetail: "Bring an objective into the existing safe route-planning workflow.",
    developers: "DEVELOPERS / API",
    developersDetail: "Call the read-only REST, MCP, and A2A discovery surfaces.",
    receipts: "AUDITABLE RECEIPTS",
    receiptsDetail: "Inspect deterministic decisions, provenance, and receipt fingerprints.",
    trust: "OBSERVED INPUTS · DETERMINISTIC POLICY · UNKNOWN STAYS UNKNOWN",
    boundary: "UNDERWRITING + USER-AUTHORIZED PUBLIC-SOURCE SYNTHESIS · NO MARKETPLACE ACTIONS",
    marketplaceBoundary: "MARKETPLACE ACTIONS DISABLED",
  },
  es: {
    eyebrow: "VALRUN / EVALUACIÓN DE TRABAJO CON IA",
    headline: "Sabe si vale la pena ejecutar una tarea de IA.",
    introduction: "Describe el trabajo. Valrun identifica las capacidades, revisa la oferta observada y evalúa costo y riesgo antes de comprometerte.",
    inspectAction: "EXAMINAR TRABAJO EN VIVO",
    underwriteAction: "ANALIZAR UNA TAREA",
    openForge: "ABRIR FORGE",
    quickLabel: "TU TAREA / EMPIEZA AQUÍ",
    quickPlaceholder: "¿Qué debe entregar el agente?",
    quickHint: "Sin cuenta · ninguna tarea se ejecuta sin tu autorización explícita",
    evidenceLabel: "UNA OBSERVACIÓN REAL DEL MERCADO",
    evidenceQuestion: "¿Qué dice realmente la evidencia?",
    observedFact: "OBSERVADO",
    rewardLabel: "RECOMPENSA",
    spendLabel: "GASTO CONOCIDO",
    decisionLabel: "LECTURA ACTUAL",
    unknown: "DESCONOCIDO",
    notEligible: "NO APTO",
    insufficientData: "DATOS INSUFICIENTES",
    evidenceCaveat: "Una publicación no es un pronóstico de ganancias. Los costos faltantes siguen desconocidos hasta evaluar la tarea.",
    noObservation: "No hay trabajo remunerado en esta vista.",
    methodHeading: "De un objetivo a una decisión defendible.",
    methodIntroduction: "Cada paso delimita lo conocido. Tú eliges los supuestos; el servidor calcula la economía.",
    methodOutcome: "PASO ACTUAL",
    boundariesLabel: "Límites de Valrun",
    controlsLabel: "Controles del motor económico",
    marketPulse: "INSTANTÁNEA DEL MERCADO",
    observedListings: "publicaciones observadas",
    paidOpportunities: "oportunidades pagadas en esta vista",
    methodLabel: "DE LA TAREA A LA DECISIÓN",
    methodSteps: [
      { title: "Describe el trabajo", detail: "Trae tu propio objetivo, aunque no haya trabajo apto en el mercado." },
      { title: "Examina la ruta", detail: "Ve las capacidades necesarias y lo que los servicios observados pueden demostrar." },
      { title: "Prueba la economía", detail: "Define tus supuestos; recibe una decisión condicional y un recibo." },
    ],
    liveWork: "TRABAJO OBSERVADO EN VIVO",
    cachedWork: "TRABAJO OBSERVADO EN CACHÉ",
    sourceStatus: "ESTADO DE OBSERVACIÓN",
    loading: "Actualizando observaciones acotadas del mercado…",
    unavailable: "Las observaciones en vivo no están disponibles. No se añadió ningún sustituto.",
    empty: "No hay trabajo observado apto en esta instantánea acotada.",
    emptyDetail: "La disponibilidad desconocida sigue siendo desconocida. Valrun nunca sustituye una oportunidad de demostración en la página pública.",
    openRadar: "ABRIR RADAR EN VIVO",
    productEntry: "PUNTOS DE ENTRADA",
    entryTitle: "Continúa con la evidencia.",
    radar: "RADAR EN VIVO",
    radarDetail: "Examina oportunidades observadas y acotadas y su elegibilidad de origen.",
    forge: "EVALUACIÓN",
    forgeDetail: "Lleva un objetivo al flujo seguro de planificación de rutas existente.",
    developers: "DESARROLLADORES / API",
    developersDetail: "Usa las superficies REST, MCP y de descubrimiento A2A de solo lectura.",
    receipts: "RECIBOS AUDITABLES",
    receiptsDetail: "Examina decisiones deterministas, procedencia y huellas de recibos.",
    trust: "DATOS OBSERVADOS · POLÍTICA DETERMINISTA · LO DESCONOCIDO NO SE INVENTA",
    boundary: "EVALUACIÓN + SÍNTESIS PÚBLICA AUTORIZADA · SIN ACCIONES DE MERCADO",
    marketplaceBoundary: "ACCIONES DE MERCADO DESHABILITADAS",
  },
  fr: {
    eyebrow: "VALRUN / ANALYSE ÉCONOMIQUE DU TRAVAIL IA",
    headline: "Sachez si une tâche IA mérite d’être exécutée.",
    introduction: "Décrivez le travail. Valrun identifie les capacités, examine l’offre observée et teste coûts et risques avant tout engagement.",
    inspectAction: "EXAMINER LE TRAVAIL EN DIRECT",
    underwriteAction: "ANALYSER UNE TÂCHE",
    openForge: "OUVRIR FORGE",
    quickLabel: "VOTRE TÂCHE / COMMENCEZ ICI",
    quickPlaceholder: "Que doit livrer l’agent ?",
    quickHint: "Sans compte · aucune tâche ne démarre sans votre autorisation explicite",
    evidenceLabel: "UNE OBSERVATION RÉELLE DU MARCHÉ",
    evidenceQuestion: "Que disent réellement les preuves ?",
    observedFact: "OBSERVÉ",
    rewardLabel: "RÉCOMPENSE",
    spendLabel: "DÉPENSE CONNUE",
    decisionLabel: "ÉTAT ACTUEL",
    unknown: "INCONNU",
    notEligible: "NON ADMISSIBLE",
    insufficientData: "DONNÉES INSUFFISANTES",
    evidenceCaveat: "Une annonce n'est pas une prévision de profit. Les coûts manquants restent inconnus jusqu'à l'analyse.",
    noObservation: "Aucune mission rémunérée dans cette vue.",
    methodHeading: "D'un objectif à une décision défendable.",
    methodIntroduction: "Chaque étape précise ce qui est connu. Vous choisissez les hypothèses ; le serveur calcule l'économie.",
    methodOutcome: "ÉTAPE ACTUELLE",
    boundariesLabel: "Limites de Valrun",
    controlsLabel: "Commandes du moteur économique",
    marketPulse: "INSTANTANÉ DU MARCHÉ",
    observedListings: "annonces observées",
    paidOpportunities: "missions rémunérées dans cette vue",
    methodLabel: "DE LA TÂCHE À LA DÉCISION",
    methodSteps: [
      { title: "Décrivez le travail", detail: "Apportez votre objectif, même sans mission admissible sur le marché." },
      { title: "Examinez la route", detail: "Voyez les capacités requises et les limites des services observés." },
      { title: "Testez l’économie", detail: "Saisissez vos hypothèses; obtenez une décision conditionnelle et un reçu." },
    ],
    liveWork: "TRAVAIL OBSERVÉ EN DIRECT",
    cachedWork: "TRAVAIL OBSERVÉ EN CACHE",
    sourceStatus: "ÉTAT DE L’OBSERVATION",
    loading: "Actualisation des observations de marché bornées…",
    unavailable: "Les observations en direct sont indisponibles. Aucun substitut n’a été inséré.",
    empty: "Aucune mission observée admissible n’est disponible dans cet instantané borné.",
    emptyDetail: "Une disponibilité inconnue reste inconnue. Valrun ne substitue jamais une opportunité de démonstration sur la page publique.",
    openRadar: "OUVRIR LE RADAR EN DIRECT",
    productEntry: "POINTS D’ENTRÉE PRODUIT",
    entryTitle: "Poursuivez avec les preuves.",
    radar: "RADAR EN DIRECT",
    radarDetail: "Examinez les opportunités observées bornées et leur admissibilité de source.",
    forge: "ANALYSE ÉCONOMIQUE",
    forgeDetail: "Transmettez un objectif au flux sûr de planification d’itinéraire existant.",
    developers: "DÉVELOPPEURS / API",
    developersDetail: "Appelez les interfaces REST, MCP et de découverte A2A en lecture seule.",
    receipts: "REÇUS AUDITABLES",
    receiptsDetail: "Examinez les décisions déterministes, la provenance et les empreintes de reçus.",
    trust: "DONNÉES OBSERVÉES · POLITIQUE DÉTERMINISTE · L’INCONNU RESTE INCONNU",
    boundary: "ANALYSE + SYNTHÈSE PUBLIQUE AUTORISÉE · AUCUNE ACTION DE MARCHÉ",
    marketplaceBoundary: "ACTIONS DE MARCHÉ DÉSACTIVÉES",
  },
} as const;

export type ProfitEngineCopy = (typeof productCopy)["en"];

export function profitEngineCopy(locale: Locale) {
  return productCopy[locale] as ProfitEngineCopy;
}
