export type ForgeLocale = "en" | "es" | "fr";

const en = {
  eyebrow: "SIGNALFORGE / FORGE LAB",
  title: "Underwrite your own task.",
  intro:
    "Define the work and state the economics you know. SignalForge underwrites first; optional public-source synthesis requires a separate Run task action.",
  task: "TASK",
  objective: "Objective",
  help: "Field help",
  objectiveHelp: "Describe the result the agent should produce. Example: Compare three public APIs and verify the findings.",
  objectivePlaceholder: "Turn 250 public product pages into validated structured data.",
  constraints: "CONSTRAINTS",
  budget: "Hard fulfillment budget (USD)",
  budgetHelp: "The maximum total fulfillment cost the route may accept. Example: 10.00.",
  policy: "Routing policy",
  policyHelp: "Choose how SignalForge should prioritize observed route evidence: value, cost, verification, or speed.",
  policyBestValue: "Best value",
  policyCheapest: "Cheapest",
  policyMostVerified: "Most verified",
  policyFastest: "Fastest",
  economics: "USER SCENARIO",
  payout: "Payout / reward (USD, optional; UNKNOWN if omitted)",
  payoutHelp: "Enter the revenue or value received if the task succeeds. Leave blank when it is unknown.",
  fulfillment: "Fulfillment cost (USD, optional; UNKNOWN if omitted)",
  fulfillmentHelp: "Enter your bounded estimate for doing the work. Catalog prices are not substituted for this task-specific cost.",
  probability: "Success probability",
  probabilityHelp: "Your explicit estimate of the chance that the task succeeds. Example: 70 means 70%.",
  review: "Human-review cost (USD)",
  reviewHelp: "Enter the expected cost of a person reviewing the result. Use 0.00 only when no review is required.",
  advanced: "Additional economic assumptions",
  verification: "Verification cost (USD)",
  verificationHelp: "Enter any separate proof or verification expense required by the task.",
  platform: "Platform / fixed fees (USD)",
  platformHelp: "Enter known fixed platform or administrative fees. Unknown fees should not be guessed.",
  failure: "Capital at risk on failure (USD)",
  failureHelp: "Enter capital that may be lost if the task fails. Do not include refundable capital unless it is genuinely at risk.",
  refundable: "Refundable capital required (USD, optional; UNKNOWN if omitted)",
  refundableHelp: "Enter capital that must be locked but is expected to be returned. It remains separate from expense.",
  margin: "Minimum acceptable margin",
  marginHelp: "The minimum conditional margin required by your policy. Example: 25 means 25%.",
  progressLabel: "Underwriting progress",
  progressUnderstanding: "Understanding objective",
  progressMapping: "Mapping capabilities",
  progressSupply: "Checking observed supply",
  progressRoute: "Building route evidence",
  progressEconomics: "Underwriting economics",
  progressDecision: "Making decision",
  progressReceipt: "Compiling receipt",
  submit: "Underwrite task",
  recalculate: "Apply assumptions",
  working: "Compiling underwriting…",
  invalidInput: "Complete the objective, budget, success probability, and human-review cost.",
  requestError: "Underwriting is temporarily unavailable. Your scenario was preserved.",
  privacy:
    "Objective decomposition may send the objective to the configured model provider. Do not include secrets or private information.",
  boundary: "UNDERWRITING DOES NOT RUN TASKS · SOURCE SYNTHESIS REQUIRES SEPARATE AUTHORIZATION",
  observedContext: "Observed catalog context",
  observedContextHelp:
    "Capability-matched listings are evidence of observed supply only. Their catalog prices are not task quotes and no provider was selected.",
  degraded: "Observed catalog context is currently degraded.",
  incomplete: "Observed supply does not cover every critical capability in this bounded snapshot.",
  available: "Bounded observed context is available for every critical capability.",
  statusAvailable: "CONTEXT AVAILABLE",
  statusIncomplete: "COVERAGE INCOMPLETE",
  statusDegraded: "CATALOG DEGRADED",
  decomposition: "Decomposition",
  decompositionGroq: "Groq objective framing",
  decompositionFallback: "Local deterministic fallback",
  decompositionProvided: "Provided objective frame",
  observedBoundary: "NOT CALLED / NOT PAID / EXECUTION DISABLED",
  userAssumption: "USER ASSUMPTION",
  derived: "DERIVED",
  unknown: "UNKNOWN",
  objectiveStage: "OBJECTIVE",
  capabilitiesStage: "CAPABILITIES",
  routeStage: "ROUTE",
  economicsStage: "ECONOMICS",
  decisionStage: "DECISION",
  expectedCost: "Expected total cost",
  residual: "Conditional residual value",
  riskAdjusted: "Risk-adjusted expected value",
  expectedMargin: "Conditional margin",
  breakEven: "Break-even payout",
  capital: "Capital required",
  refundableCapital: "Refundable capital · not expense",
  blockers: "What prevents a complete decision",
  limitations: "Route evidence limitations",
  receipt: "AUDITABLE RECEIPT",
  download: "Download receipt JSON",
  fingerprint: "Economic decision fingerprint · not a digital signature",
  noOptions: "No observed option was promoted into a route candidate.",
  edit: "Change the scenario and apply assumptions to recalculate on the server.",
  synthesisTitle: "RUN A BOUNDED TASK",
  synthesisTag: "USER-AUTHORIZED / PUBLIC SOURCES ONLY",
  synthesisFingerprint: "SHA-256 fingerprint, not a signature",
  synthesisUsage: "Observed model usage",
  synthesisCost: "Cost calculated from measured tokens at published price; provider charge unknown",
  synthesisIntro: "Research and synthesis from public sources is the one enabled execution route. It never calls catalog services, claims marketplace work, or pays anyone.",
  synthesisSources: "Public HTTPS sources (one URL per line, 1–10)",
  synthesisSourcesHelp: "Enter public pages to synthesize. Example: https://www.example.org/report. Private, local, redirected, oversized, and unsupported pages are rejected.",
  synthesisRoute: "ROUTE · FETCH PUBLIC TEXT → GROQ SYNTHESIS → SOURCE-BOUND FINDINGS",
  synthesisEstimate: "Expected model cost: unknown until sources are read. Published-price ceiling:",
  synthesisAuthorization: "Max authorized model spend: $0.01 · one call · no purchases or marketplace writes.",
  synthesisRun: "Run task",
  synthesisWorking: "Reading public sources and synthesizing…",
  synthesisError: "Source synthesis was not completed. Check the public URLs and try a new run.",
  synthesisFindings: "Source-bound findings",
  synthesisLimitations: "Limitations",
  synthesisReceipt: "Download execution receipt",
  synthesisSaved: "Execution saved to your history.",
  synthesisSaveFailed: "Task complete. We couldn't save the execution to your history.",
  synthesisGuest: "Guest result: download the receipt to keep it. Sign in for private history.",
};

export type ForgeCopy = typeof en;

const es: ForgeCopy = {
  ...en,
  eyebrow: "SIGNALFORGE / LABORATORIO FORGE",
  title: "Evalúa tu propia tarea.",
  intro:
    "Define el trabajo y los datos económicos conocidos. SignalForge evalúa primero; la síntesis opcional de fuentes públicas requiere otra autorización.",
  task: "TAREA",
  objective: "Objetivo",
  help: "Ayuda del campo",
  objectiveHelp: "Describe el resultado que debe producir el agente. Ejemplo: compara tres API públicas y verifica los hallazgos.",
  objectivePlaceholder: "Convierte 250 páginas públicas de producto en datos estructurados y validados.",
  constraints: "RESTRICCIONES",
  budget: "Presupuesto máximo de cumplimiento (USD)",
  budgetHelp: "El costo máximo total que puede aceptar la ruta. Ejemplo: 10.00.",
  policy: "Política de ruta",
  policyHelp: "Elige cómo SignalForge prioriza la evidencia: valor, costo, verificación o velocidad.",
  policyBestValue: "Mejor valor",
  policyCheapest: "Más económica",
  policyMostVerified: "Más verificada",
  policyFastest: "Más rápida",
  economics: "ESCENARIO DEL USUARIO",
  payout: "Pago / recompensa (USD, opcional; DESCONOCIDO si se omite)",
  payoutHelp: "Indica el ingreso o valor recibido si la tarea tiene éxito. Déjalo vacío si se desconoce.",
  fulfillment: "Costo de cumplimiento (USD, opcional; DESCONOCIDO si se omite)",
  fulfillmentHelp: "Indica tu estimación acotada para realizar el trabajo. Los precios de catálogo no reemplazan este costo específico.",
  probability: "Probabilidad de éxito",
  probabilityHelp: "Tu estimación explícita de éxito. Ejemplo: 70 significa 70%.",
  review: "Costo de revisión humana (USD)",
  reviewHelp: "Indica el costo esperado de una revisión humana. Usa 0.00 solo si no se necesita revisión.",
  advanced: "Supuestos económicos adicionales",
  verification: "Costo de verificación (USD)",
  verificationHelp: "Indica cualquier gasto separado de prueba o verificación.",
  platform: "Tarifas fijas / plataforma (USD)",
  platformHelp: "Indica tarifas fijas conocidas. No adivines tarifas desconocidas.",
  failure: "Capital en riesgo si falla (USD)",
  failureHelp: "Indica el capital que podría perderse si falla. No incluyas capital reembolsable salvo que realmente esté en riesgo.",
  refundable: "Capital reembolsable requerido (USD, opcional; DESCONOCIDO si se omite)",
  refundableHelp: "Indica el capital bloqueado que se espera recuperar. Se mantiene separado del gasto.",
  margin: "Margen mínimo aceptable",
  marginHelp: "El margen condicional mínimo de tu política. Ejemplo: 25 significa 25%.",
  progressLabel: "Progreso del análisis",
  progressUnderstanding: "Entendiendo el objetivo",
  progressMapping: "Mapeando capacidades",
  progressSupply: "Revisando oferta observada",
  progressRoute: "Construyendo evidencia de ruta",
  progressEconomics: "Evaluando la economía",
  progressDecision: "Tomando la decisión",
  progressReceipt: "Compilando el recibo",
  submit: "Evaluar tarea",
  recalculate: "Aplicar supuestos",
  working: "Compilando evaluación…",
  invalidInput: "Completa el objetivo, presupuesto, probabilidad de éxito y costo de revisión humana.",
  requestError: "La evaluación no está disponible temporalmente. Tu escenario se conservó.",
  privacy:
    "La descomposición puede enviar el objetivo al proveedor de modelo configurado. No incluyas secretos ni información privada.",
  boundary: "LA EVALUACIÓN NO EJECUTA TAREAS · LA SÍNTESIS REQUIERE AUTORIZACIÓN SEPARADA",
  observedContext: "Contexto de catálogo observado",
  observedContextHelp:
    "Los listados compatibles son solo evidencia de oferta observada. Sus precios no son cotizaciones de la tarea y no se seleccionó ningún proveedor.",
  degraded: "El contexto del catálogo observado está degradado.",
  incomplete: "La muestra limitada no cubre todas las capacidades críticas.",
  available: "Hay contexto observado limitado para cada capacidad crítica.",
  statusAvailable: "CONTEXTO DISPONIBLE",
  statusIncomplete: "COBERTURA INCOMPLETA",
  statusDegraded: "CATÁLOGO DEGRADADO",
  decomposition: "Descomposición",
  decompositionGroq: "Interpretación del objetivo con Groq",
  decompositionFallback: "Alternativa determinista local",
  decompositionProvided: "Marco de objetivo proporcionado",
  observedBoundary: "NO LLAMADO / NO PAGADO / EJECUCIÓN DESHABILITADA",
  userAssumption: "SUPUESTO DEL USUARIO",
  derived: "DERIVADO",
  unknown: "DESCONOCIDO",
  objectiveStage: "OBJETIVO",
  capabilitiesStage: "CAPACIDADES",
  routeStage: "RUTA",
  economicsStage: "ECONOMÍA",
  decisionStage: "DECISIÓN",
  expectedCost: "Costo total esperado",
  residual: "Valor residual condicional",
  riskAdjusted: "Valor esperado ajustado al riesgo",
  expectedMargin: "Margen condicional",
  breakEven: "Pago de equilibrio",
  capital: "Capital requerido",
  refundableCapital: "Capital reembolsable · no es gasto",
  blockers: "Qué impide una decisión completa",
  limitations: "Límites de la evidencia de ruta",
  receipt: "RECIBO AUDITABLE",
  download: "Descargar recibo JSON",
  fingerprint: "Huella de la decisión económica · no es una firma digital",
  noOptions: "Ninguna opción observada se convirtió en candidata de ruta.",
  edit: "Modifica el escenario y aplica los supuestos para recalcular en el servidor.",
  synthesisTitle: "EJECUTAR UNA TAREA ACOTADA",
  synthesisTag: "AUTORIZACIÓN DEL USUARIO / SOLO FUENTES PÚBLICAS",
  synthesisFingerprint: "Huella SHA-256, no es una firma",
  synthesisUsage: "Uso observado del modelo",
  synthesisCost: "Costo calculado con tokens medidos y precio publicado; cargo del proveedor desconocido",
  synthesisIntro: "La investigación y síntesis de fuentes públicas es la única ruta de ejecución habilitada. No llama servicios del catálogo, reclama trabajos ni realiza pagos.",
  synthesisSources: "Fuentes HTTPS públicas (una URL por línea, 1–10)",
  synthesisSourcesHelp: "Indica páginas públicas para sintetizar. Ejemplo: https://www.example.org/report. Se rechazan páginas privadas, locales, redirigidas, demasiado grandes o no compatibles.",
  synthesisRoute: "RUTA · LEER TEXTO PÚBLICO → SÍNTESIS CON GROQ → HALLAZGOS CON FUENTES",
  synthesisEstimate: "Costo esperado del modelo: desconocido hasta leer las fuentes. Límite con precio publicado:",
  synthesisAuthorization: "Gasto máximo autorizado del modelo: $0.01 · una llamada · sin compras ni acciones de mercado.",
  synthesisRun: "Ejecutar tarea",
  synthesisWorking: "Leyendo fuentes públicas y sintetizando…",
  synthesisError: "La síntesis no se completó. Revisa las URL públicas e intenta una ejecución nueva.",
  synthesisFindings: "Hallazgos con fuentes",
  synthesisLimitations: "Limitaciones",
  synthesisReceipt: "Descargar recibo de ejecución",
  synthesisSaved: "Ejecución guardada en tu historial.",
  synthesisSaveFailed: "Tarea completa. No pudimos guardar la ejecución en tu historial.",
  synthesisGuest: "Resultado de invitado: descarga el recibo para conservarlo. Inicia sesión para tener historial privado.",
};

const fr: ForgeCopy = {
  ...en,
  eyebrow: "SIGNALFORGE / LABORATOIRE FORGE",
  title: "Analysez votre propre mission.",
  intro:
    "Définissez le travail et les données économiques connues. SignalForge analyse d’abord ; la synthèse facultative de sources publiques exige une autorisation distincte.",
  task: "MISSION",
  objective: "Objectif",
  help: "Aide du champ",
  objectiveHelp: "Décrivez le résultat attendu. Exemple : comparer trois API publiques et vérifier les conclusions.",
  objectivePlaceholder: "Transformer 250 pages produit publiques en données structurées et validées.",
  constraints: "CONTRAINTES",
  budget: "Budget maximal d’exécution (USD)",
  budgetHelp: "Le coût total maximal que l’itinéraire peut accepter. Exemple : 10.00.",
  policy: "Politique de routage",
  policyHelp: "Choisissez la priorité des preuves : valeur, coût, vérification ou rapidité.",
  policyBestValue: "Meilleur rapport valeur/coût",
  policyCheapest: "Moins chère",
  policyMostVerified: "Plus vérifiée",
  policyFastest: "Plus rapide",
  economics: "SCÉNARIO UTILISATEUR",
  payout: "Rémunération (USD, facultative ; INCONNUE si omise)",
  payoutHelp: "Indiquez le revenu ou la valeur reçue en cas de réussite. Laissez vide si elle est inconnue.",
  fulfillment: "Coût de réalisation (USD, facultatif ; INCONNU si omis)",
  fulfillmentHelp: "Indiquez votre estimation bornée pour réaliser le travail. Les prix catalogue ne remplacent pas ce coût propre à la tâche.",
  probability: "Probabilité de réussite",
  probabilityHelp: "Votre estimation explicite de réussite. Exemple : 70 signifie 70 %.",
  review: "Coût de revue humaine (USD)",
  reviewHelp: "Indiquez le coût attendu d’une revue humaine. Utilisez 0.00 seulement si aucune revue n’est requise.",
  advanced: "Hypothèses économiques supplémentaires",
  verification: "Coût de vérification (USD)",
  verificationHelp: "Indiquez toute dépense séparée de preuve ou de vérification.",
  platform: "Frais fixes / plateforme (USD)",
  platformHelp: "Indiquez les frais fixes connus. Ne devinez pas les frais inconnus.",
  failure: "Capital à risque en cas d’échec (USD)",
  failureHelp: "Indiquez le capital susceptible d’être perdu en cas d’échec. N’incluez pas le capital remboursable sauf risque réel.",
  refundable: "Capital remboursable requis (USD, facultatif ; INCONNU si omis)",
  refundableHelp: "Indiquez le capital immobilisé mais supposé restitué. Il reste séparé des dépenses.",
  margin: "Marge minimale acceptable",
  marginHelp: "La marge conditionnelle minimale de votre politique. Exemple : 25 signifie 25 %.",
  progressLabel: "Progression de l’analyse",
  progressUnderstanding: "Compréhension de l’objectif",
  progressMapping: "Cartographie des capacités",
  progressSupply: "Vérification de l’offre observée",
  progressRoute: "Construction des preuves d’itinéraire",
  progressEconomics: "Analyse économique",
  progressDecision: "Décision en cours",
  progressReceipt: "Compilation du reçu",
  submit: "Analyser la mission",
  recalculate: "Appliquer les hypothèses",
  working: "Compilation de l’analyse…",
  invalidInput: "Renseignez l’objectif, le budget, la probabilité de réussite et le coût de revue humaine.",
  requestError: "L’analyse est temporairement indisponible. Votre scénario a été conservé.",
  privacy:
    "La décomposition peut transmettre l’objectif au fournisseur de modèle configuré. N’incluez aucun secret ni donnée privée.",
  boundary: "L’ANALYSE N’EXÉCUTE PAS DE TÂCHE · LA SYNTHÈSE EXIGE UNE AUTORISATION DISTINCTE",
  observedContext: "Contexte de catalogue observé",
  observedContextHelp:
    "Les offres correspondantes sont uniquement des indices d’offre observée. Leurs prix ne sont pas des devis et aucun fournisseur n’a été sélectionné.",
  degraded: "Le contexte du catalogue observé est actuellement dégradé.",
  incomplete: "L’échantillon borné ne couvre pas toutes les capacités critiques.",
  available: "Un contexte observé borné existe pour chaque capacité critique.",
  statusAvailable: "CONTEXTE DISPONIBLE",
  statusIncomplete: "COUVERTURE INCOMPLÈTE",
  statusDegraded: "CATALOGUE DÉGRADÉ",
  decomposition: "Décomposition",
  decompositionGroq: "Interprétation de l’objectif par Groq",
  decompositionFallback: "Repli déterministe local",
  decompositionProvided: "Cadre d’objectif fourni",
  observedBoundary: "NON APPELÉ / NON PAYÉ / EXÉCUTION DÉSACTIVÉE",
  userAssumption: "HYPOTHÈSE UTILISATEUR",
  derived: "DÉRIVÉ",
  unknown: "INCONNU",
  objectiveStage: "OBJECTIF",
  capabilitiesStage: "CAPACITÉS",
  routeStage: "ROUTE",
  economicsStage: "ÉCONOMIE",
  decisionStage: "DÉCISION",
  expectedCost: "Coût total attendu",
  residual: "Valeur résiduelle conditionnelle",
  riskAdjusted: "Valeur attendue ajustée au risque",
  expectedMargin: "Marge conditionnelle",
  breakEven: "Rémunération d’équilibre",
  capital: "Capital requis",
  refundableCapital: "Capital remboursable · pas une dépense",
  blockers: "Ce qui empêche une décision complète",
  limitations: "Limites des preuves de routage",
  receipt: "REÇU AUDITABLE",
  download: "Télécharger le reçu JSON",
  fingerprint: "Empreinte de la décision économique · pas une signature numérique",
  noOptions: "Aucune option observée n’a été transformée en candidate de route.",
  edit: "Modifiez le scénario puis appliquez les hypothèses pour recalculer côté serveur.",
  synthesisTitle: "EXÉCUTER UNE TÂCHE BORNÉE",
  synthesisTag: "AUTORISATION UTILISATEUR / SOURCES PUBLIQUES UNIQUEMENT",
  synthesisFingerprint: "Empreinte SHA-256, pas une signature",
  synthesisUsage: "Utilisation du modèle observée",
  synthesisCost: "Coût calculé à partir des jetons mesurés et du tarif publié ; facturation réelle inconnue",
  synthesisIntro: "La recherche et la synthèse de sources publiques constituent la seule route d’exécution active. Aucun service du catalogue, mission de marché ou paiement n’est engagé.",
  synthesisSources: "Sources HTTPS publiques (une URL par ligne, 1 à 10)",
  synthesisSourcesHelp: "Indiquez des pages publiques à synthétiser. Exemple : https://www.example.org/report. Les pages privées, locales, redirigées, trop volumineuses ou incompatibles sont refusées.",
  synthesisRoute: "ROUTE · LIRE LE TEXTE PUBLIC → SYNTHÈSE GROQ → CONSTATS SOURCÉS",
  synthesisEstimate: "Coût attendu du modèle : inconnu avant lecture des sources. Plafond au tarif publié :",
  synthesisAuthorization: "Dépense modèle maximale autorisée : 0,01 $ · un appel · aucun achat ni action de marché.",
  synthesisRun: "Exécuter la tâche",
  synthesisWorking: "Lecture des sources publiques et synthèse…",
  synthesisError: "La synthèse n’a pas abouti. Vérifiez les URL publiques et relancez une nouvelle tâche.",
  synthesisFindings: "Constats sourcés",
  synthesisLimitations: "Limites",
  synthesisReceipt: "Télécharger le reçu d’exécution",
  synthesisSaved: "Exécution enregistrée dans votre historique.",
  synthesisSaveFailed: "Tâche terminée. Nous n’avons pas pu l’enregistrer dans votre historique.",
  synthesisGuest: "Résultat invité : téléchargez le reçu pour le conserver. Connectez-vous pour un historique privé.",
};

export const forgeCopy: Record<ForgeLocale, ForgeCopy> = { en, es, fr };
