export type ForgeLocale = "en" | "es" | "fr";

const en = {
  eyebrow: "SIGNALFORGE / FORGE LAB",
  title: "Underwrite your own task.",
  intro:
    "Define the work and state the economics you know. SignalForge maps capabilities, checks observed supply context, and calculates a conditional decision without executing anything.",
  task: "TASK",
  objective: "Objective",
  objectivePlaceholder: "Turn 250 public product pages into validated structured data.",
  constraints: "CONSTRAINTS",
  budget: "Hard fulfillment budget (USD)",
  policy: "Routing policy",
  policyBestValue: "Best value",
  policyCheapest: "Cheapest",
  policyMostVerified: "Most verified",
  policyFastest: "Fastest",
  economics: "USER SCENARIO",
  payout: "Payout / reward (USD, optional; UNKNOWN if omitted)",
  fulfillment: "Fulfillment cost (USD, optional; UNKNOWN if omitted)",
  probability: "Success probability",
  review: "Human-review cost (USD)",
  advanced: "Additional economic assumptions",
  verification: "Verification cost (USD)",
  platform: "Platform / fixed fees (USD)",
  failure: "Capital at risk on failure (USD)",
  refundable: "Refundable capital required (USD, optional; UNKNOWN if omitted)",
  margin: "Minimum acceptable margin",
  submit: "Underwrite task",
  recalculate: "Apply assumptions",
  working: "Compiling underwriting…",
  invalidInput: "Complete the objective, budget, success probability, and human-review cost.",
  requestError: "Underwriting is temporarily unavailable. Your scenario was preserved.",
  privacy:
    "Objective decomposition may send the objective to the configured model provider. Do not include secrets or private information.",
  boundary: "UNDERWRITING ONLY · NO SERVICE CALLS · NO PAYMENTS · EXECUTION DISABLED",
  observedContext: "Observed catalog context",
  observedContextHelp:
    "Capability-matched listings are evidence of observed supply only. Their catalog prices are not task quotes and no provider was selected.",
  degraded: "Observed catalog context is currently degraded.",
  incomplete: "Observed supply does not cover every critical capability in this bounded snapshot.",
  available: "Bounded observed context is available for every critical capability.",
  statusAvailable: "CONTEXT AVAILABLE",
  statusIncomplete: "COVERAGE INCOMPLETE",
  statusDegraded: "CATALOG DEGRADED",
  decomposition: "Decomposition",
  decompositionGroq: "Groq objective framing",
  decompositionFallback: "Local deterministic fallback",
  decompositionProvided: "Provided objective frame",
  observedBoundary: "NOT CALLED / NOT PAID / EXECUTION DISABLED",
  userAssumption: "USER ASSUMPTION",
  derived: "DERIVED",
  unknown: "UNKNOWN",
  objectiveStage: "OBJECTIVE",
  capabilitiesStage: "CAPABILITIES",
  routeStage: "ROUTE",
  economicsStage: "ECONOMICS",
  decisionStage: "DECISION",
  expectedCost: "Expected total cost",
  residual: "Conditional residual value",
  riskAdjusted: "Risk-adjusted expected value",
  expectedMargin: "Conditional margin",
  breakEven: "Break-even payout",
  capital: "Capital required",
  refundableCapital: "Refundable capital · not expense",
  blockers: "What prevents a complete decision",
  limitations: "Route evidence limitations",
  receipt: "AUDITABLE RECEIPT",
  download: "Download receipt JSON",
  fingerprint: "Economic decision fingerprint · not a digital signature",
  noOptions: "No observed option was promoted into a route candidate.",
  edit: "Change the scenario and apply assumptions to recalculate on the server.",
};

export type ForgeCopy = typeof en;

const es: ForgeCopy = {
  ...en,
  eyebrow: "SIGNALFORGE / LABORATORIO FORGE",
  title: "Evalúa tu propia tarea.",
  intro:
    "Define el trabajo y declara los datos económicos conocidos. SignalForge mapea capacidades, revisa el contexto observado y calcula una decisión condicional sin ejecutar nada.",
  task: "TAREA",
  objective: "Objetivo",
  objectivePlaceholder: "Convierte 250 páginas públicas de producto en datos estructurados y validados.",
  constraints: "RESTRICCIONES",
  budget: "Presupuesto máximo de cumplimiento (USD)",
  policy: "Política de ruta",
  policyBestValue: "Mejor valor",
  policyCheapest: "Más económica",
  policyMostVerified: "Más verificada",
  policyFastest: "Más rápida",
  economics: "ESCENARIO DEL USUARIO",
  payout: "Pago / recompensa (USD, opcional; DESCONOCIDO si se omite)",
  fulfillment: "Costo de cumplimiento (USD, opcional; DESCONOCIDO si se omite)",
  probability: "Probabilidad de éxito",
  review: "Costo de revisión humana (USD)",
  advanced: "Supuestos económicos adicionales",
  verification: "Costo de verificación (USD)",
  platform: "Tarifas fijas / plataforma (USD)",
  failure: "Capital en riesgo si falla (USD)",
  refundable: "Capital reembolsable requerido (USD, opcional; DESCONOCIDO si se omite)",
  margin: "Margen mínimo aceptable",
  submit: "Evaluar tarea",
  recalculate: "Aplicar supuestos",
  working: "Compilando evaluación…",
  invalidInput: "Completa el objetivo, presupuesto, probabilidad de éxito y costo de revisión humana.",
  requestError: "La evaluación no está disponible temporalmente. Tu escenario se conservó.",
  privacy:
    "La descomposición puede enviar el objetivo al proveedor de modelo configurado. No incluyas secretos ni información privada.",
  boundary: "SOLO EVALUACIÓN · SIN LLAMADAS · SIN PAGOS · EJECUCIÓN DESHABILITADA",
  observedContext: "Contexto de catálogo observado",
  observedContextHelp:
    "Los listados compatibles son solo evidencia de oferta observada. Sus precios no son cotizaciones de la tarea y no se seleccionó ningún proveedor.",
  degraded: "El contexto del catálogo observado está degradado.",
  incomplete: "La muestra limitada no cubre todas las capacidades críticas.",
  available: "Hay contexto observado limitado para cada capacidad crítica.",
  statusAvailable: "CONTEXTO DISPONIBLE",
  statusIncomplete: "COBERTURA INCOMPLETA",
  statusDegraded: "CATÁLOGO DEGRADADO",
  decomposition: "Descomposición",
  decompositionGroq: "Interpretación del objetivo con Groq",
  decompositionFallback: "Alternativa determinista local",
  decompositionProvided: "Marco de objetivo proporcionado",
  observedBoundary: "NO LLAMADO / NO PAGADO / EJECUCIÓN DESHABILITADA",
  userAssumption: "SUPUESTO DEL USUARIO",
  derived: "DERIVADO",
  unknown: "DESCONOCIDO",
  objectiveStage: "OBJETIVO",
  capabilitiesStage: "CAPACIDADES",
  routeStage: "RUTA",
  economicsStage: "ECONOMÍA",
  decisionStage: "DECISIÓN",
  expectedCost: "Costo total esperado",
  residual: "Valor residual condicional",
  riskAdjusted: "Valor esperado ajustado al riesgo",
  expectedMargin: "Margen condicional",
  breakEven: "Pago de equilibrio",
  capital: "Capital requerido",
  refundableCapital: "Capital reembolsable · no es gasto",
  blockers: "Qué impide una decisión completa",
  limitations: "Límites de la evidencia de ruta",
  receipt: "RECIBO AUDITABLE",
  download: "Descargar recibo JSON",
  fingerprint: "Huella de la decisión económica · no es una firma digital",
  noOptions: "Ninguna opción observada se convirtió en candidata de ruta.",
  edit: "Modifica el escenario y aplica los supuestos para recalcular en el servidor.",
};

const fr: ForgeCopy = {
  ...en,
  eyebrow: "SIGNALFORGE / LABORATOIRE FORGE",
  title: "Analysez votre propre mission.",
  intro:
    "Définissez le travail et déclarez les données économiques connues. SignalForge cartographie les capacités, examine le contexte observé et calcule une décision conditionnelle sans rien exécuter.",
  task: "MISSION",
  objective: "Objectif",
  objectivePlaceholder: "Transformer 250 pages produit publiques en données structurées et validées.",
  constraints: "CONTRAINTES",
  budget: "Budget maximal d’exécution (USD)",
  policy: "Politique de routage",
  policyBestValue: "Meilleur rapport valeur/coût",
  policyCheapest: "Moins chère",
  policyMostVerified: "Plus vérifiée",
  policyFastest: "Plus rapide",
  economics: "SCÉNARIO UTILISATEUR",
  payout: "Rémunération (USD, facultative ; INCONNUE si omise)",
  fulfillment: "Coût de réalisation (USD, facultatif ; INCONNU si omis)",
  probability: "Probabilité de réussite",
  review: "Coût de revue humaine (USD)",
  advanced: "Hypothèses économiques supplémentaires",
  verification: "Coût de vérification (USD)",
  platform: "Frais fixes / plateforme (USD)",
  failure: "Capital à risque en cas d’échec (USD)",
  refundable: "Capital remboursable requis (USD, facultatif ; INCONNU si omis)",
  margin: "Marge minimale acceptable",
  submit: "Analyser la mission",
  recalculate: "Appliquer les hypothèses",
  working: "Compilation de l’analyse…",
  invalidInput: "Renseignez l’objectif, le budget, la probabilité de réussite et le coût de revue humaine.",
  requestError: "L’analyse est temporairement indisponible. Votre scénario a été conservé.",
  privacy:
    "La décomposition peut transmettre l’objectif au fournisseur de modèle configuré. N’incluez aucun secret ni donnée privée.",
  boundary: "ANALYSE UNIQUEMENT · AUCUN APPEL · AUCUN PAIEMENT · EXÉCUTION DÉSACTIVÉE",
  observedContext: "Contexte de catalogue observé",
  observedContextHelp:
    "Les offres correspondantes sont uniquement des indices d’offre observée. Leurs prix ne sont pas des devis et aucun fournisseur n’a été sélectionné.",
  degraded: "Le contexte du catalogue observé est actuellement dégradé.",
  incomplete: "L’échantillon borné ne couvre pas toutes les capacités critiques.",
  available: "Un contexte observé borné existe pour chaque capacité critique.",
  statusAvailable: "CONTEXTE DISPONIBLE",
  statusIncomplete: "COUVERTURE INCOMPLÈTE",
  statusDegraded: "CATALOGUE DÉGRADÉ",
  decomposition: "Décomposition",
  decompositionGroq: "Interprétation de l’objectif par Groq",
  decompositionFallback: "Repli déterministe local",
  decompositionProvided: "Cadre d’objectif fourni",
  observedBoundary: "NON APPELÉ / NON PAYÉ / EXÉCUTION DÉSACTIVÉE",
  userAssumption: "HYPOTHÈSE UTILISATEUR",
  derived: "DÉRIVÉ",
  unknown: "INCONNU",
  objectiveStage: "OBJECTIF",
  capabilitiesStage: "CAPACITÉS",
  routeStage: "ROUTE",
  economicsStage: "ÉCONOMIE",
  decisionStage: "DÉCISION",
  expectedCost: "Coût total attendu",
  residual: "Valeur résiduelle conditionnelle",
  riskAdjusted: "Valeur attendue ajustée au risque",
  expectedMargin: "Marge conditionnelle",
  breakEven: "Rémunération d’équilibre",
  capital: "Capital requis",
  refundableCapital: "Capital remboursable · pas une dépense",
  blockers: "Ce qui empêche une décision complète",
  limitations: "Limites des preuves de routage",
  receipt: "REÇU AUDITABLE",
  download: "Télécharger le reçu JSON",
  fingerprint: "Empreinte de la décision économique · pas une signature numérique",
  noOptions: "Aucune option observée n’a été transformée en candidate de route.",
  edit: "Modifiez le scénario puis appliquez les hypothèses pour recalculer côté serveur.",
};

export const forgeCopy: Record<ForgeLocale, ForgeCopy> = { en, es, fr };
