import type { ForgeLocale } from "./copy";

const en = {
  summary: "Decision / your scenario", basis: "Conditional economics based on your assumptions—not verified earnings.",
  cost: "Expected cost", ev: "Risk-adjusted EV", payout: "Payout assumption", coverage: "Evidence coverage",
  missing: "Critical capabilities without observed supply evidence", details: "Inspect objective, capabilities and economic inputs",
  retry: "Retry saving this analysis", saveHelp: "Your result and receipt are still available. Retry saving; this will not rerun the analysis or create a duplicate.",
  sources: "Public source URLs", sourceHelp: "Paste 1–10 public HTTPS URLs, one per line. This field accepts links, not instructions.",
  ready: "Valid URL format · availability checked when research runs", invalid: "Invalid URL · use a public HTTPS page without credentials or fragments", count: "Enter 1–10 different public HTTPS URLs.",
  objective: "Enter a task of at least 12 characters above before running research.", disabled: "Research is unavailable because a safe price ceiling cannot be established.",
  run: "Run public-source research", source: "Source", update: "Update decision",
  invalid_source: "A source URL is invalid or duplicated. Correct the indicated URL.",
  blocked_source: "The source is blocked by the public-network safety policy. Use another public page.",
  fetch_failed: "The source could not be fetched. It may be unavailable or rejecting server requests. Check the page or use another source.",
  redirect_rejected: "The source redirects. Open it yourself and paste its final public HTTPS address; Valrun does not follow redirects.",
  content_unusable: "The source is too large or does not provide usable HTML/plain text. Use a smaller public text page.",
  provider_unavailable: "The research provider is unavailable in this environment. Changing your URLs will not fix this.",
  model_failed: "The model did not return a usable, cited result. No completed research receipt was produced. A new attempt may use another model call.",
  capacity_unavailable: "Research capacity is temporarily unavailable. Try again later.",
  duplicate_execution: "This research request was already submitted. Do not repeat it automatically.",
  request_invalid: "Check the objective and source URLs before submitting.",
  network: "The request could not be completed. Check your connection before starting a new run.",
};
type Copy = typeof en;
const es: Copy = {
  summary: "Decisión / tu escenario", basis: "Economía condicional según tus supuestos; no son ganancias verificadas.",
  cost: "Costo esperado", ev: "VE ajustado al riesgo", payout: "Pago supuesto", coverage: "Cobertura de evidencia",
  missing: "Capacidades críticas sin evidencia de oferta observada", details: "Inspeccionar objetivo, capacidades y datos económicos",
  retry: "Reintentar guardar este análisis", saveHelp: "El resultado y el recibo siguen disponibles. Guardar de nuevo no repite el análisis ni crea duplicados.",
  sources: "URL de fuentes públicas", sourceHelp: "Pega entre 1 y 10 URL HTTPS públicas, una por línea. Este campo acepta enlaces, no instrucciones.",
  ready: "Formato válido · disponibilidad comprobada al investigar", invalid: "URL inválida · usa HTTPS público sin credenciales ni fragmentos", count: "Introduce entre 1 y 10 URL HTTPS públicas diferentes.",
  objective: "Introduce arriba una tarea de al menos 12 caracteres antes de investigar.", disabled: "La investigación no está disponible porque no se puede establecer un límite de costo seguro.",
  run: "Investigar fuentes públicas", source: "Fuente", update: "Actualizar decisión",
  invalid_source: "Una URL es inválida o está duplicada. Corrige la URL indicada.",
  blocked_source: "La política de red pública bloquea esta fuente. Usa otra página pública.",
  fetch_failed: "No se pudo consultar la fuente. Puede estar caída o rechazar solicitudes del servidor. Revisa la página o usa otra fuente.",
  redirect_rejected: "La fuente redirige. Ábrela y pega su dirección HTTPS pública final; Valrun no sigue redirecciones.",
  content_unusable: "La fuente es demasiado grande o no ofrece HTML/texto utilizable. Usa una página de texto pública más pequeña.",
  provider_unavailable: "El proveedor no está disponible en este entorno. Cambiar las URL no lo resolverá.",
  model_failed: "El modelo no produjo un resultado útil con citas. No se generó un recibo completo. Reintentar puede consumir otra llamada.",
  capacity_unavailable: "La capacidad está temporalmente agotada. Inténtalo más tarde.",
  duplicate_execution: "Esta solicitud ya se envió. No la repitas automáticamente.",
  request_invalid: "Revisa el objetivo y las URL antes de enviar.", network: "La solicitud no se completó. Revisa tu conexión antes de iniciar otra ejecución.",
};
const fr: Copy = {
  summary: "Décision / votre scénario", basis: "Économie conditionnelle fondée sur vos hypothèses, pas des gains vérifiés.",
  cost: "Coût attendu", ev: "VE ajustée au risque", payout: "Rémunération supposée", coverage: "Couverture des preuves",
  missing: "Capacités critiques sans preuve d’offre observée", details: "Inspecter l’objectif, les capacités et les données économiques",
  retry: "Réessayer l’enregistrement", saveHelp: "Le résultat et le reçu restent disponibles. Réessayer ne relance pas l’analyse et ne crée pas de doublon.",
  sources: "URL des sources publiques", sourceHelp: "Collez 1 à 10 URL HTTPS publiques, une par ligne. Ce champ accepte des liens, pas des instructions.",
  ready: "Format valide · disponibilité vérifiée lors de la recherche", invalid: "URL invalide · utilisez HTTPS public sans identifiants ni fragments", count: "Indiquez 1 à 10 URL HTTPS publiques différentes.",
  objective: "Saisissez une tâche d’au moins 12 caractères ci-dessus avant la recherche.", disabled: "La recherche est indisponible faute de plafond de coût sûr.",
  run: "Rechercher dans les sources publiques", source: "Source", update: "Actualiser la décision",
  invalid_source: "Une URL est invalide ou en double. Corrigez l’URL indiquée.",
  blocked_source: "Cette source est bloquée par la politique réseau. Utilisez une autre page publique.",
  fetch_failed: "La source est inaccessible ou refuse les requêtes du serveur. Vérifiez la page ou changez de source.",
  redirect_rejected: "La source redirige. Ouvrez-la et collez son adresse HTTPS publique finale ; Valrun ne suit pas les redirections.",
  content_unusable: "La source est trop grande ou sans contenu HTML/texte exploitable. Utilisez une page publique plus petite.",
  provider_unavailable: "Le fournisseur est indisponible dans cet environnement. Changer les URL ne résoudra pas ce problème.",
  model_failed: "Le modèle n’a pas produit de résultat exploitable avec citations. Aucun reçu complet n’a été généré. Réessayer peut consommer un autre appel.",
  capacity_unavailable: "La capacité est temporairement indisponible. Réessayez plus tard.",
  duplicate_execution: "Cette demande a déjà été envoyée. Ne la répétez pas automatiquement.",
  request_invalid: "Vérifiez l’objectif et les URL avant l’envoi.", network: "La demande n’a pas abouti. Vérifiez votre connexion avant une nouvelle exécution.",
};
export const experienceCopy: Record<ForgeLocale, Copy> = { en, es, fr };
