import type { Locale } from "@/i18n/routing";

const copy = {
  en: {
    lab: "V2 VISUAL LAB — NOT PRODUCTION UI",
    title: "Three instruments for one economic truth.",
    intro: "A controlled study of how SignalForge could make evidence, route competition, and conditional economics visible.",
    concept: "Concept",
    state: "Data state",
    real: "REAL",
    unknown: "UNKNOWN",
    degraded: "DEGRADED",
    empty: "EMPTY",
    simulated: "LAB STATE SIMULATION",
    current: "Current data status",
    loading: "Reading bounded observations…",
    unavailable: "Observed data unavailable. No substitute was inserted.",
    noData: "No observed opportunity is available in this bounded snapshot.",
    notProduction: "Lab states test visual resilience. They are not marketplace truth.",
    execution: "EXECUTION NOT ENABLED",
    source: "Source",
    observed: "Observed",
    reward: "Observed reward",
    spend: "Known external spend",
    cost: "Estimated fulfillment cost",
    risk: "Risk adjustment",
    residual: "Conditional residual value",
    bond: "Refundable capital / bond",
    unknownValue: "UNKNOWN",
    provenance: "Provenance",
    missing: "Missing evidence",
    inspect: "Inspect datum",
    axes: "X / economic completeness · Y / observed reward (log scale)",
    coverage: "Bounded observations only. This is not exhaustive market coverage.",
    objective: "OBJECTIVE",
    capabilities: "REQUIRED CAPABILITIES",
    options: "OBSERVED OPTIONS",
    gates: "CONSTRAINT GATES",
    route: "SELECTED ROUTE",
    contract: "ECONOMIC CONTRACT",
    noRoute: "No selected route: the current observed domain exposes matching options, not a justified RouteCandidateSet.",
    optionReason: "Unit catalog price is not a task quote.",
    selectedDatum: "Selected observation",
    modeHint: "Use the four states to inspect truth, gaps, degradation, and absence.",
    verdictQuestion: "IS THE WORK WORTH DOING?",
    insufficient: "INSUFFICIENT DATA",
    notEligible: "NOT ELIGIBLE",
  },
  es: {
    lab: "LABORATORIO VISUAL V2 — NO ES LA INTERFAZ DE PRODUCCIÓN",
    title: "Tres instrumentos para una sola verdad económica.",
    intro: "Un estudio controlado de cómo SignalForge puede hacer visibles la evidencia, la competencia entre rutas y la economía condicional.",
    concept: "Concepto",
    state: "Estado de datos",
    real: "REAL",
    unknown: "DESCONOCIDO",
    degraded: "DEGRADADO",
    empty: "VACÍO",
    simulated: "SIMULACIÓN DE ESTADO DEL LABORATORIO",
    current: "Estado actual de los datos",
    loading: "Leyendo observaciones acotadas…",
    unavailable: "Los datos observados no están disponibles. No se añadió ningún sustituto.",
    noData: "No hay una oportunidad observada en esta instantánea acotada.",
    notProduction: "Los estados del laboratorio prueban la resiliencia visual. No representan la realidad del mercado.",
    execution: "EJECUCIÓN NO HABILITADA",
    source: "Fuente",
    observed: "Observado",
    reward: "Recompensa observada",
    spend: "Gasto externo conocido",
    cost: "Costo estimado de cumplimiento",
    risk: "Ajuste de riesgo",
    residual: "Valor residual condicional",
    bond: "Capital reembolsable / garantía",
    unknownValue: "DESCONOCIDO",
    provenance: "Procedencia",
    missing: "Evidencia faltante",
    inspect: "Inspeccionar dato",
    axes: "X / integridad económica · Y / recompensa observada (escala logarítmica)",
    coverage: "Solo observaciones acotadas. No es una cobertura exhaustiva del mercado.",
    objective: "OBJETIVO",
    capabilities: "CAPACIDADES REQUERIDAS",
    options: "OPCIONES OBSERVADAS",
    gates: "FILTROS DE RESTRICCIÓN",
    route: "RUTA SELECCIONADA",
    contract: "CONTRATO ECONÓMICO",
    noRoute: "No hay una ruta seleccionada: el dominio observado actual expone opciones coincidentes, no un RouteCandidateSet justificado.",
    optionReason: "El precio unitario del catálogo no es una cotización de la tarea.",
    selectedDatum: "Observación seleccionada",
    modeHint: "Usa los cuatro estados para inspeccionar verdad, brechas, degradación y ausencia.",
    verdictQuestion: "¿VALE LA PENA HACER EL TRABAJO?",
    insufficient: "DATOS INSUFICIENTES",
    notEligible: "NO ELEGIBLE",
  },
  fr: {
    lab: "LABORATOIRE VISUEL V2 — PAS L’INTERFACE DE PRODUCTION",
    title: "Trois instruments pour une seule vérité économique.",
    intro: "Une étude contrôlée de la manière dont SignalForge peut rendre visibles les preuves, la compétition des itinéraires et l’économie conditionnelle.",
    concept: "Concept",
    state: "État des données",
    real: "RÉEL",
    unknown: "INCONNU",
    degraded: "DÉGRADÉ",
    empty: "VIDE",
    simulated: "SIMULATION D’ÉTAT DU LABORATOIRE",
    current: "État actuel des données",
    loading: "Lecture des observations bornées…",
    unavailable: "Les données observées sont indisponibles. Aucun substitut n’a été inséré.",
    noData: "Aucune opportunité observée n’est disponible dans cet instantané borné.",
    notProduction: "Les états du laboratoire testent la résilience visuelle. Ils ne représentent pas la réalité du marché.",
    execution: "EXÉCUTION NON ACTIVÉE",
    source: "Source",
    observed: "Observé",
    reward: "Récompense observée",
    spend: "Dépense externe connue",
    cost: "Coût d’exécution estimé",
    risk: "Ajustement du risque",
    residual: "Valeur résiduelle conditionnelle",
    bond: "Capital remboursable / caution",
    unknownValue: "INCONNU",
    provenance: "Provenance",
    missing: "Preuves manquantes",
    inspect: "Inspecter la donnée",
    axes: "X / complétude économique · Y / récompense observée (échelle logarithmique)",
    coverage: "Observations bornées uniquement. Il ne s’agit pas d’une couverture exhaustive du marché.",
    objective: "OBJECTIF",
    capabilities: "CAPACITÉS REQUISES",
    options: "OPTIONS OBSERVÉES",
    gates: "FILTRES DE CONTRAINTE",
    route: "ITINÉRAIRE SÉLECTIONNÉ",
    contract: "CONTRAT ÉCONOMIQUE",
    noRoute: "Aucun itinéraire sélectionné : le domaine observé actuel expose des options correspondantes, pas un RouteCandidateSet justifié.",
    optionReason: "Le prix unitaire du catalogue n’est pas un devis pour la tâche.",
    selectedDatum: "Observation sélectionnée",
    modeHint: "Utilisez les quatre états pour inspecter la vérité, les lacunes, la dégradation et l’absence.",
    verdictQuestion: "LE TRAVAIL EN VAUT-IL LA PEINE ?",
    insufficient: "DONNÉES INSUFFISANTES",
    notEligible: "NON ÉLIGIBLE",
  },
} as const;

export type LabCopy = (typeof copy)["en"];
export const labCopy = (locale: Locale): LabCopy => copy[locale] as LabCopy;
