export type AccountLocale = "en" | "es" | "fr";

const en = {
  signIn: "Sign in",
  title: "Keep your SignalForge work.",
  intro: "Sign in to save analyses, receipts and history. SignalForge remains fully usable without an account.",
  google: "Continue with Google",
  or: "or",
  email: "Email",
  emailPlaceholder: "you@example.com",
  send: "Send secure sign-in link",
  sent: "Check your email for a secure sign-in link.",
  safeError: "Sign-in is temporarily unavailable. Please try again.",
  continueGuest: "Continue without an account",
  analyses: "My analyses",
  account: "Account",
  signOut: "Sign out",
  menu: "Account menu",
  save: "Save this analysis",
  saveHelp: "Create a free account to keep this run and access it later.",
  saved: "Saved to your history.",
  saveFailed: "Analysis complete. We couldn't save it to your history.",
  saving: "Saving…",
  unavailable: "Account persistence is not configured in this environment.",
  close: "Close sign-in",
};

export type AccountCopy = typeof en;
const es: AccountCopy = {
  ...en,
  signIn: "Iniciar sesión",
  title: "Conserva tu trabajo en SignalForge.",
  intro: "Inicia sesión para guardar análisis, recibos e historial. SignalForge sigue siendo totalmente usable sin una cuenta.",
  google: "Continuar con Google",
  or: "o",
  email: "Correo electrónico",
  emailPlaceholder: "tu@ejemplo.com",
  send: "Enviar enlace seguro",
  sent: "Revisa tu correo para abrir el enlace seguro.",
  safeError: "El inicio de sesión no está disponible temporalmente. Inténtalo de nuevo.",
  continueGuest: "Continuar sin cuenta",
  analyses: "Mis análisis",
  account: "Cuenta",
  signOut: "Cerrar sesión",
  menu: "Menú de cuenta",
  save: "Guardar este análisis",
  saveHelp: "Crea una cuenta gratuita para conservar esta ejecución y abrirla más tarde.",
  saved: "Guardado en tu historial.",
  saveFailed: "El análisis terminó, pero no pudimos guardarlo en tu historial.",
  saving: "Guardando…",
  unavailable: "La persistencia de cuentas no está configurada en este entorno.",
  close: "Cerrar acceso",
};
const fr: AccountCopy = {
  ...en,
  signIn: "Se connecter",
  title: "Conservez votre travail SignalForge.",
  intro: "Connectez-vous pour enregistrer analyses, reçus et historique. SignalForge reste entièrement utilisable sans compte.",
  google: "Continuer avec Google",
  or: "ou",
  email: "E-mail",
  emailPlaceholder: "vous@exemple.com",
  send: "Envoyer le lien sécurisé",
  sent: "Consultez votre messagerie pour ouvrir le lien sécurisé.",
  safeError: "La connexion est temporairement indisponible. Réessayez.",
  continueGuest: "Continuer sans compte",
  analyses: "Mes analyses",
  account: "Compte",
  signOut: "Se déconnecter",
  menu: "Menu du compte",
  save: "Enregistrer cette analyse",
  saveHelp: "Créez un compte gratuit pour conserver cette analyse et la rouvrir plus tard.",
  saved: "Enregistrée dans votre historique.",
  saveFailed: "L’analyse est terminée, mais son enregistrement a échoué.",
  saving: "Enregistrement…",
  unavailable: "La persistance des comptes n’est pas configurée dans cet environnement.",
  close: "Fermer la connexion",
};

export const accountCopy: Record<AccountLocale, AccountCopy> = { en, es, fr };
