import type { Locale } from "@/i18n/routing";
const en = {
  title: "My analyses", eyebrow: "VALRUN / PRIVATE LEDGER",
  intro: "Your decisions, evidence and receipts. Saved snapshots never re-run when opened.",
  newTask: "Underwrite a task", account: "Account", empty: "Your ledger starts with a task.",
  emptyDetail: "Use Forge to evaluate an objective. Completed analyses are saved here when you are signed in.",
  unavailable: "History is temporarily unavailable. You can still underwrite tasks. Try refreshing.",
  partial: "Some history could not be loaded. Counts cover only available records.",
  scope: "Most recent 100 records per workflow—not lifetime totals.",
  analyses: "Underwriting snapshots", executions: "Source syntheses", unresolved: "Analyses with blockers",
  open: "Open snapshot", unknown: "Unknown", invalid: "Snapshot could not be verified",
  payout: "Scenario payout", cost: "Scenario cost", ev: "Conditional EV",
  evidence: "Observed options", assumptions: "User assumptions—not measured profit",
  historical: "Evidence as recorded then; not a current availability check.",
  usage: "Usage-priced model cost", charge: "Provider-billed charge unknown",
  sources: "Public sources", calls: "Model calls", receipt: "Receipt fingerprint",
  underwrite: "Underwriting", synthesis: "Source synthesis", completed: "Completed",
  statuses: { conditionally_profitable: "Conditionally profitable", conditionally_marginal: "Conditionally marginal", conditionally_uneconomic: "Conditionally uneconomic", insufficient_data: "Insufficient data", not_eligible: "Not eligible", unroutable: "Unroutable" },
};
type LedgerCopy = typeof en;
const es: LedgerCopy = {
  title: "Mis análisis", eyebrow: "VALRUN / REGISTRO PRIVADO",
  intro: "Tus decisiones, evidencia y recibos. Abrir una instantánea guardada no vuelve a ejecutarla.",
  newTask: "Evaluar una tarea", account: "Cuenta", empty: "Tu registro empieza con una tarea.",
  emptyDetail: "Usa Forge para evaluar un objetivo. Los análisis completados se guardan aquí si has iniciado sesión.",
  unavailable: "El historial no está disponible temporalmente. Puedes seguir evaluando tareas. Actualiza la página.",
  partial: "Parte del historial no se pudo cargar. Los conteos incluyen solo registros disponibles.",
  scope: "Los 100 registros más recientes por flujo; no son totales históricos.",
  analyses: "Evaluaciones guardadas", executions: "Síntesis de fuentes", unresolved: "Análisis con bloqueos",
  open: "Abrir instantánea", unknown: "Desconocido", invalid: "No se pudo verificar la instantánea",
  payout: "Pago del escenario", cost: "Costo del escenario", ev: "VE condicional",
  evidence: "Opciones observadas", assumptions: "Supuestos del usuario; no son ganancias medidas",
  historical: "Evidencia registrada entonces; no es una comprobación de disponibilidad actual.",
  usage: "Costo del modelo según uso", charge: "Cargo facturado por el proveedor desconocido",
  sources: "Fuentes públicas", calls: "Llamadas al modelo", receipt: "Huella del recibo",
  underwrite: "Evaluación", synthesis: "Síntesis de fuentes", completed: "Completada",
  statuses: { conditionally_profitable: "Rentable bajo condiciones", conditionally_marginal: "Marginal bajo condiciones", conditionally_uneconomic: "No rentable bajo condiciones", insufficient_data: "Datos insuficientes", not_eligible: "No apto", unroutable: "Sin ruta viable" },
};
const fr: LedgerCopy = {
  title: "Mes analyses", eyebrow: "VALRUN / REGISTRE PRIVÉ",
  intro: "Vos décisions, preuves et reçus. Ouvrir un instantané ne relance jamais le calcul.",
  newTask: "Analyser une tâche", account: "Compte", empty: "Votre registre commence par une tâche.",
  emptyDetail: "Utilisez Forge pour évaluer un objectif. Vos analyses terminées sont enregistrées lorsque vous êtes connecté.",
  unavailable: "L’historique est temporairement indisponible. L’analyse reste accessible. Actualisez la page.",
  partial: "Une partie de l’historique est indisponible. Les compteurs concernent uniquement les enregistrements chargés.",
  scope: "Les 100 derniers enregistrements par workflow ; pas de totaux à vie.",
  analyses: "Analyses enregistrées", executions: "Synthèses des sources", unresolved: "Analyses avec blocages",
  open: "Ouvrir l’instantané", unknown: "Inconnu", invalid: "Impossible de vérifier l’instantané",
  payout: "Rémunération du scénario", cost: "Coût du scénario", ev: "VA conditionnelle",
  evidence: "Options observées", assumptions: "Hypothèses utilisateur ; pas des bénéfices mesurés",
  historical: "Preuves enregistrées à l’époque ; pas une vérification de disponibilité actuelle.",
  usage: "Coût du modèle selon l’usage", charge: "Montant facturé par le fournisseur inconnu",
  sources: "Sources publiques", calls: "Appels au modèle", receipt: "Empreinte du reçu",
  underwrite: "Analyse", synthesis: "Synthèse des sources", completed: "Terminée",
  statuses: { conditionally_profitable: "Rentable sous conditions", conditionally_marginal: "Marginal sous conditions", conditionally_uneconomic: "Non rentable sous conditions", insufficient_data: "Données insuffisantes", not_eligible: "Non éligible", unroutable: "Aucune route viable" },
};
export const ledgerCopy: Record<Locale, LedgerCopy> = { en, es, fr };
