[theme]
base = "light"
primaryColor = "#173b65"
backgroundColor = "#f5f4f0"
secondaryBackgroundColor = "#eeede8"
textColor = "#191c20"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
